### PR TITLE
Add previous variable snippet

### PR DESCRIPTION
**Pull request by andreifilip123**
Hello !

Thanks for the extension, I find it really useful. 
However, I keep finding myself in the situation where I need to use the previous state/props in order to replace some `componentWillReceiveProps` or `componentDidUpdate` with hooks. Therefore, I created a snippet for this. 
It still has some work to be done unfortunately but I didn't have the time to look into it that much. The thing that needs to be done is to make the first letter uppercase/lowercase in some places but I didn't find any way to do this yet. If you're more experienced with snippets and have any suggestions, I'd gladly make changes to this.

Thanks ! 😄

### CODE REVIEW

**Comment by iamandiradu** [comment]
That would be neat!

**Comment by alDuncanson** [comment]
Thanks for the pull request @andreifilip123 ! Unfortunately right now I am having issues publishing and updating my extension and I'm currently working with VS marketplace support on the issue.

When that's fixed I can look into your pull request more! What is the functionality you want with this exactly?

**Comment by andreifilip123** [comment]
This functionality:
https://reactjs.org/docs/hooks-faq.html#how-to-get-the-previous-props-or-state

**Comment by alDuncanson** [comment]
> This functionality:
> https://reactjs.org/docs/hooks-faq.html#how-to-get-the-previous-props-or-state

Oh nice! That would be a helpful addition :+1:

**Comment by andreifilip123** [comment]
Since [react redux 7.1.0](https://github.com/reduxjs/react-redux/releases/tag/v7.1.0) added hooks, I thought it would be a nice addition to have them in this extension as well. 
I added 3 hooks: 
- `uss` for `useSelector`
- `usdf` for `useDispatch`
- `usd` for creating dispatch functions

I know the last two should be named the opposite but I think that users will want to create dispatch functions more than to write the simple useDispatch so therefore I used `usd` for creating dispatch functions. 

Hope this will get merged soon :)

**Pull request merged**
